#!/bin/bash

export G4INSTALL=/Users/charles-josephnaim/Desktop/NN/geant_install
export ROOTINSTALL=/opt/homebrew
export G4DATA=$G4INSTALL/share/Geant4/data
export PYTHIA8_DIR=/Users/charles-josephnaim/Desktop/EIC/ePIC/releases

export G4NEUTRONHPDATA=$G4DATA/G4NDL4.7.1
export G4LEDATA=$G4DATA/G4EMLOW8.6.1
export G4LEVELGAMMADATA=$G4DATA/PhotonEvaporation6.1
export G4RADIOACTIVEDATA=$G4DATA/RadioactiveDecay6.1.2
export G4PARTICLEXSDATA=$G4DATA/G4PARTICLEXS4.1
export G4SAIDXSDATA=$G4DATA/G4SAIDDATA2.0
export G4ABLADATA=$G4DATA/G4ABLA3.3
export G4INCLDATA=$G4DATA/G4INCL1.2
export G4PIIDATA=$G4DATA/G4PII1.3
export G4REALSURFACEDATA=$G4DATA/RealSurface2.2
export G4ENSDFSTATEDATA=$G4DATA/G4ENSDFSTATE3.0
export G4EMLOW8=$G4DATA/G4EMLOW8.6.1

export PATH=$G4INSTALL/bin:$ROOTINSTALL/bin:$PATH
export LD_LIBRARY_PATH=$G4INSTALL/lib:$ROOTINSTALL/lib:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$G4INSTALL/lib:$ROOTINSTALL/lib:$DYLD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=/opt/homebrew/Cellar/root/6.36.04/lib:$DYLD_LIBRARY_PATH

make

./mySimulation init_vis.mac 
